#pragma once

#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include <cmath>
#include <algorithm>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <set>
#include <map>
#include <list>
#include <bitset>
#include <cstring>
#include <stack>
#include <climits>
#include <functional>
#include <cassert>

using std::cout;
using std::cin;
using std::endl;
using std::string;
using std::vector;
using std::unordered_map;
using std::unordered_set;
using std::priority_queue;
using std::queue;
using std::pair;
using std::fstream;
using std::ifstream;
using std::ofstream;
using std::getline;
using std::stoi;
using std::stod;
using std::sqrt;
using std::sort;
using std::reverse;
using std::max;
using std::min;
using std::ios_base;
using std::size_t;
using std::greater;
using std::swap;
using std::to_string;
using std::set;
using std::map;
using std::list;
using std::count;
using std::begin;
using std::end;
using std::bitset;
using std::__gcd;
using std::memset;
using std::stack;
using std::function;